server:
  port: 9041

spring:
  application:
    name: "securityapplication"

  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC
    username: root
    password: Mastanbi@12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka/
#info:
#  app:
#    name: "accounts"
#    description: " Bank Accounts Application"
#    version: "1.0.0"